"""
Custom Tools for Roadmap Agent
"""

import json
import os
from datetime import datetime


def analyze_job_market(domain: str, location: str = "global") -> dict:
    """
    Analyzes job market data for a specific domain.
    
    Args:
        domain: Job domain/role (e.g., "Data Analyst", "Frontend Developer")
        location: Geographic location for job search (default: "global")
    
    Returns:
        Dictionary with job market insights
    """

    return {
        "domain": domain,
        "location": location,
        "status": "success",
        "message": f"Job market analysis completed for {domain}. Use Google Search tool to find current job requirements.",
        "suggestions": [
            f"Search for: '{domain} job requirements 2025'",
            f"Search for: '{domain} skills in demand'",
            f"Search for: 'entry level {domain} interview questions'",
        ]
    }


def find_learning_resources(
    topic: str, 
    resource_type: str = "mixed", 
    difficulty: str = "beginner"
) -> dict:
    """
    Finds learning resources for a specific topic.
    
    Args:
        topic: Learning topic (e.g., "Python basics", "SQL queries")
        resource_type: Type of resource ("video", "article", "interactive", "mixed")
        difficulty: Difficulty level ("beginner", "intermediate", "advanced")
    
    Returns:
        Dictionary with resource finding status and search suggestions
    """
    
    search_queries = []
    
    if resource_type in ["video", "mixed"]:
        search_queries.append(f"{topic} tutorial {difficulty} 2025")
        search_queries.append(f"best {topic} course for beginners")
    
    if resource_type in ["article", "mixed"]:
        search_queries.append(f"{topic} guide {difficulty}")
        search_queries.append(f"learn {topic} {difficulty}")
    
    if resource_type in ["interactive", "mixed"]:
        search_queries.append(f"{topic} practice exercises")
        search_queries.append(f"{topic} hands-on projects")
    
    return {
        "topic": topic,
        "resource_type": resource_type,
        "difficulty": difficulty,
        "status": "success",
        "message": "Use Google Search with these queries to find current resources",
        "suggested_searches": search_queries,
        "platforms": {
            "video": ["YouTube", "Udemy", "Coursera", "freeCodeCamp"],
            "article": ["Medium", "Dev.to", "Official documentation"],
            "interactive": ["LeetCode", "HackerRank", "Exercism", "Codecademy"],
        }
    }


def save_roadmap_to_file(
    roadmap_content: str, 
    filename: str,
    format_type: str = "markdown"
) -> dict:
    """
    Saves the roadmap to a file.
    
    Args:
        roadmap_content: The complete roadmap text
        filename: Desired filename (e.g., "my_roadmap.md")
        format_type: Output format ("markdown" or "json")
    
    Returns:
        Dictionary with save status
    """
    try:
        # Ensure proper file extension
        if format_type == "markdown" and not filename.endswith(".md"):
            filename += ".md"
        elif format_type == "json" and not filename.endswith(".json"):
            filename += ".json"
        
        # Add metadata header
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        if format_type == "markdown":
            full_content = f"""---
Generated: {timestamp}
Type: Career Preparation Roadmap
---

{roadmap_content}

---
**Note:** This roadmap was generated by an AI assistant. Adjust based on your learning pace and circumstances.
Remember to track your progress and don't hesitate to modify the plan as needed.
"""
            with open(filename, "w", encoding="utf-8") as f:
                f.write(full_content)
        
        elif format_type == "json":
            # Structure the roadmap as JSON
            roadmap_data = {
                "metadata": {
                    "generated": timestamp,
                    "type": "career_preparation_roadmap",
                },
                "content": roadmap_content,
            }
            with open(filename, "w", encoding="utf-8") as f:
                json.dump(roadmap_data, f, indent=2, ensure_ascii=False)
        
        return {
            "status": "success",
            "filename": filename,
            "path": os.path.abspath(filename),
            "message": f"Roadmap saved successfully to {filename}",
        }
    
    except Exception as e:
        return {
            "status": "error",
            "message": f"Failed to save roadmap: {str(e)}",
        }


def validate_roadmap_structure(roadmap_content: str) -> dict:
    """
    Validates that a roadmap has proper structure.
    
    Args:
        roadmap_content: Roadmap text to validate
    
    Returns:
        Dictionary with validation results
    """
    issues = []
    
    # Check for week headers
    week_count = roadmap_content.lower().count("week ")
    if week_count < 4:
        issues.append(f"Expected 4 weeks, found {week_count}")
    
    # Check for daily breakdowns
    day_count = roadmap_content.lower().count("day ")
    if day_count < 20:  # At least 5 days per week * 4 weeks
        issues.append(f"Insufficient daily breakdowns (found {day_count})")
    
    # Check for key sections
    required_sections = ["objective", "concepts", "practice"]
    missing_sections = [
        section for section in required_sections 
        if section not in roadmap_content.lower()
    ]
    
    if missing_sections:
        issues.append(f"Missing sections: {', '.join(missing_sections)}")
    
    return {
        "valid": len(issues) == 0,
        "issues": issues,
        "week_count": week_count,
        "day_count": day_count,
    }